#!/usr/bin/env python3
"""Generate i18n-bundle.js by inlining zh-CN.json and en.json as JS."""
import json
from pathlib import Path

ROOT = Path('/Users/xuanxuan/Downloads/作品网站')
zh = json.loads((ROOT / 'i18n/zh-CN.json').read_text())
en = json.loads((ROOT / 'i18n/en.json').read_text())

bundle = {'zh': zh, 'en': en}

js = (
    '/* Auto-generated by tools/build_i18n_bundle.py — DO NOT EDIT BY HAND.\n'
    '   Source of truth: i18n/zh-CN.json + i18n/en.json. */\n'
    'window.__I18N_BUNDLE__ = '
    + json.dumps(bundle, ensure_ascii=False, indent=2)
    + ';\n'
)

out = ROOT / 'i18n-bundle.js'
out.write_text(js)
print(f'✅ Wrote {out}  ({out.stat().st_size} bytes)')
print(f'   zh keys (top-level): {sorted(zh.keys())}')
print(f'   en keys (top-level): {sorted(en.keys())}')
